# Generated by Django 4.1 on 2023-01-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
