# Generated by Django 4.1 on 2023-01-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_name_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
